name: publish

on: [push]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the hello-world Docker image
      run: |
        echo $CR_PAT | docker login ghcr.io -u YourAccountOrGHOrgaNameHere --password-stdin
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
    - name: Github Package
      run: docker build . --tag ghcr.io/karthik892/angular-quiz-app:latest
    - name: dcoker image
      run: docker run ghcr.io/karthik892/angular-quiz-app:latest
    - name: get docker image
      run: docker push ghcr.io/karthik892/angular-quiz-app:latest
